// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Pv9DDuTieGdZyZK2xpYx0daDC_g8_D4',
    appId: '1:900680184742:web:554b1514195a8ae83e5567',
    messagingSenderId: '900680184742',
    projectId: 'safestreets-a32d6',
    authDomain: 'safestreets-a32d6.firebaseapp.com',
    storageBucket: 'safestreets-a32d6.appspot.com',
    measurementId: 'G-NDETRS0V17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDchpbEfDWrpxAv9A_po_Oyy2E9Wg8o7RM',
    appId: '1:900680184742:android:014a6d0eda74cbd83e5567',
    messagingSenderId: '900680184742',
    projectId: 'safestreets-a32d6',
    storageBucket: 'safestreets-a32d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP3UnLfrlKyN6GC1xqAhtzsV-ngoCnou4',
    appId: '1:900680184742:ios:71ffbea89a1ef4493e5567',
    messagingSenderId: '900680184742',
    projectId: 'safestreets-a32d6',
    storageBucket: 'safestreets-a32d6.appspot.com',
    iosClientId: '900680184742-09trdb3802a5l41e1mbhirfbvcbod98v.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
