// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBalXW7bdb97Rc8vI8Nd2FkKQxcYqqZLVQ',
    appId: '1:901483938215:web:6e571c7e728f0649fd3682',
    messagingSenderId: '901483938215',
    projectId: 'safehome-352402',
    authDomain: 'safehome-352402.firebaseapp.com',
    storageBucket: 'safehome-352402.appspot.com',
    measurementId: 'G-S7VZNE3LBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7IOw7g8Wu1YctfjoAwLX1-DYfs1EdHAg',
    appId: '1:901483938215:android:3f69f4b66c998029fd3682',
    messagingSenderId: '901483938215',
    projectId: 'safehome-352402',
    storageBucket: 'safehome-352402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_fjxS7l3OheSmtnk8c0H9jYe8FCK2e8c',
    appId: '1:901483938215:ios:11c03ed78aca405dfd3682',
    messagingSenderId: '901483938215',
    projectId: 'safehome-352402',
    storageBucket: 'safehome-352402.appspot.com',
    iosClientId: '901483938215-vmnhk9g6puu3e8s2i5u84aofj39lmqk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
